### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by johnraz** [nip3o/pytest-stepwise#15]
Hi there,

Just a quick request / thought.

Is there anything blocking a release of the Python 3.7 compatibility fix?

I like this plugin and it would be sad to see people bounce from using it just because the version released in pypi is not compatible with Python 3.7

Thanks !

**Comment by nip3o** [comment]
Hi and sorry for the late response! The functionality of stepwise has as just been merged into pytest (https://github.com/pytest-dev/pytest/pull/4147), and to avoid compatibility issues with future pytest releases there will not be any more releases of pytest-stepwise. You can use the master version until the next pytest release. I'll update the README with this info soon. :)

**Comment by johnraz** [comment]
That’s an awesome news and thanks for the feedback !!!
