### ISSUE TITLE
Tests that are actual failures

### ISSUE THREAD

**Issue by rockstarabhi** [nip3o/pytest-stepwise#4]
Hi,

Thank you for this plugin. This is fantastic. To make it even better, can the below option be added?

Currently, this plugin runs all tests until a test fails, and then continue next test run from where the last run failed. What if the failed test is due to an actual application issue (a genuine test failure)? Is there a way to skip that failed test and start from next test?

Regards,
Abhilash

**Comment by nip3o** [comment]
Hello!
It is possible to ignore one failing test by using the `--skip` option. The last failed test will still run, but the tests will then continue with the next test and run until a new test fails. Does this work for your use case?

**Comment by rockstarabhi** [comment]
Yes, this is a work around for my requirement. Thanks.
